"""Validate Question 1 tiles, masks, YOLO labels, and repatched imagery."""

import argparse
import csv
import json
from collections import defaultdict
from pathlib import Path

import cv2
import numpy as np
from PIL import Image


def load_metadata(run_dir: Path) -> list[dict[str, str]]:
    """Load tile metadata generated by run_pipeline.py."""
    with (
        run_dir / "tile_metadata.csv"
    ).open(encoding="utf-8") as stream:
        return list(csv.DictReader(stream))


def validate_label_file(
    path: Path,
    tile_size: int,
) -> tuple[np.ndarray, list[str]]:
    """Rasterize one YOLO segmentation label file and report syntax errors."""
    rebuilt = np.zeros(
        (tile_size, tile_size),
        dtype=np.uint8,
    )
    failures: list[str] = []

    for line_number, line in enumerate(
        path.read_text(
            encoding="utf-8"
        ).splitlines(),
        start=1,
    ):
        values = line.split()
        if not values:
            continue

        if values[0] not in {"0", "1"}:
            failures.append(
                f"{path.name}:{line_number} "
                "invalid class ID"
            )
            continue

        if (
            len(values) < 7
            or len(values) % 2 == 0
        ):
            failures.append(
                f"{path.name}:{line_number} "
                "invalid polygon row"
            )
            continue

        try:
            points = np.asarray(
                [
                    float(value)
                    for value in values[1:]
                ],
                dtype=np.float32,
            ).reshape(-1, 2)
        except ValueError:
            failures.append(
                f"{path.name}:{line_number} "
                "non-numeric coordinate"
            )
            continue

        if (
            not np.isfinite(points).all()
            or (points < 0).any()
            or (points > 1).any()
        ):
            failures.append(
                f"{path.name}:{line_number} "
                "coordinate outside [0, 1]"
            )
            continue

        pixels = (
            points * tile_size
        ).astype(np.int32)

        if (
            len(np.unique(pixels, axis=0)) < 3
            or cv2.contourArea(pixels) <= 0
        ):
            failures.append(
                f"{path.name}:{line_number} "
                "degenerate polygon"
            )
            continue

        cv2.fillPoly(
            rebuilt,
            [pixels],
            int(values[0]) + 1,
        )

    return rebuilt, failures


def validate(
    run_dir: Path,
    tile_size: int = 1024,
) -> bool:
    """Validate exported files and write qa/validation.json."""
    metadata = load_metadata(run_dir)
    failures: list[str] = []

    if not metadata:
        failures.append(
            "tile_metadata.csv contains no rows"
        )

    tile_names = [
        row["tile"]
        for row in metadata
    ]
    if len(tile_names) != len(set(tile_names)):
        failures.append(
            "duplicate tile names in tile_metadata.csv"
        )

    grouped: dict[
        str,
        list[dict[str, str]],
    ] = defaultdict(list)

    for row in metadata:
        grouped[row["source"]].append(row)

    for row in metadata:
        tile = row["tile"]
        valid_width = int(
            row["valid_width"]
        )
        valid_height = int(
            row["valid_height"]
        )

        image_path = (
            run_dir
            / "images"
            / f"{tile}.png"
        )
        mask_path = (
            run_dir
            / "masks"
            / f"{tile}.png"
        )
        overlay_path = (
            run_dir
            / "overlays"
            / f"{tile}.png"
        )
        label_path = (
            run_dir
            / "labels"
            / f"{tile}.txt"
        )

        for path in (
            image_path,
            mask_path,
            overlay_path,
            label_path,
        ):
            if not path.exists():
                failures.append(
                    "missing file: "
                    f"{path.relative_to(run_dir)}"
                )

        if any(
            not path.exists()
            for path in (
                image_path,
                mask_path,
                label_path,
            )
        ):
            continue

        image = np.asarray(
            Image.open(image_path)
        )
        mask = np.asarray(
            Image.open(mask_path)
        )

        if image.shape != (
            tile_size,
            tile_size,
        ):
            failures.append(
                f"{tile}: image shape "
                f"is {image.shape}"
            )

        if mask.shape != (
            tile_size,
            tile_size,
        ):
            failures.append(
                f"{tile}: mask shape "
                f"is {mask.shape}"
            )
            continue

        if not set(
            np.unique(mask)
        ).issubset({0, 1, 2}):
            failures.append(
                f"{tile}: mask contains "
                "invalid class values"
            )

        if (
            mask[valid_height:, :].any()
            or mask[:, valid_width:].any()
        ):
            failures.append(
                f"{tile}: padded area "
                "contains annotations"
            )

        rebuilt, label_failures = (
            validate_label_file(
                label_path,
                tile_size,
            )
        )
        failures.extend(label_failures)

        if not np.array_equal(
            rebuilt,
            mask,
        ):
            difference = int(
                np.count_nonzero(
                    rebuilt != mask
                )
            )
            failures.append(
                f"{tile}: YOLO polygon/mask "
                f"mismatch ({difference} pixels)"
            )

    for source, rows in grouped.items():
        original_width = int(
            rows[0]["original_width"]
        )
        original_height = int(
            rows[0]["original_height"]
        )
        stem = Path(source).stem

        expected_rows = (
            original_height
            + tile_size
            - 1
        ) // tile_size
        expected_columns = (
            original_width
            + tile_size
            - 1
        ) // tile_size

        expected_tiles = (
            expected_rows
            * expected_columns
        )
        if len(rows) != expected_tiles:
            failures.append(
                f"{source}: expected "
                f"{expected_tiles} tiles, "
                f"found {len(rows)}"
            )

        rebuilt_image = np.zeros(
            (
                original_height,
                original_width,
            ),
            dtype=np.uint8,
        )
        rebuilt_mask = np.zeros_like(
            rebuilt_image
        )

        positions: set[
            tuple[int, int]
        ] = set()

        for row in rows:
            x0 = int(row["x_offset"])
            y0 = int(row["y_offset"])
            valid_width = int(
                row["valid_width"]
            )
            valid_height = int(
                row["valid_height"]
            )
            tile = row["tile"]

            position = (x0, y0)
            if position in positions:
                failures.append(
                    f"{source}: duplicate "
                    f"tile position {position}"
                )
                continue
            positions.add(position)

            image = np.asarray(
                Image.open(
                    run_dir
                    / "images"
                    / f"{tile}.png"
                )
            )
            mask = np.asarray(
                Image.open(
                    run_dir
                    / "masks"
                    / f"{tile}.png"
                )
            )

            rebuilt_image[
                y0 : y0 + valid_height,
                x0 : x0 + valid_width,
            ] = image[
                :valid_height,
                :valid_width,
            ]
            rebuilt_mask[
                y0 : y0 + valid_height,
                x0 : x0 + valid_width,
            ] = mask[
                :valid_height,
                :valid_width,
            ]

        repatched_image_path = (
            run_dir
            / "repatched"
            / f"{stem}_processed.png"
        )
        repatched_mask_path = (
            run_dir
            / "repatched"
            / f"{stem}_mask.png"
        )
        repatched_overlay_path = (
            run_dir
            / "repatched"
            / f"{stem}_overlay.png"
        )

        if not repatched_image_path.exists():
            failures.append(
                f"{source}: missing "
                "repatched processed image"
            )
        else:
            repatched_image = np.asarray(
                Image.open(
                    repatched_image_path
                )
            )
            if not np.array_equal(
                rebuilt_image,
                repatched_image,
            ):
                failures.append(
                    f"{source}: repatched "
                    "processed image mismatch"
                )

        if not repatched_mask_path.exists():
            failures.append(
                f"{source}: missing "
                "repatched mask"
            )
        else:
            repatched_mask = np.asarray(
                Image.open(
                    repatched_mask_path
                )
            )
            if not np.array_equal(
                rebuilt_mask,
                repatched_mask,
            ):
                failures.append(
                    f"{source}: repatched "
                    "mask mismatch"
                )

        if not repatched_overlay_path.exists():
            failures.append(
                f"{source}: missing "
                "repatched overlay"
            )
        else:
            overlay_size = Image.open(
                repatched_overlay_path
            ).size
            if overlay_size != (
                original_width,
                original_height,
            ):
                failures.append(
                    f"{source}: repatched "
                    "overlay has wrong dimensions"
                )

    result = {
        "passed": not failures,
        "tiles_checked": len(metadata),
        "sources_checked": len(grouped),
        "failures": failures,
        "scope": (
            "Structural validation only. "
            "Manual QA is still required "
            "to confirm astronomical class "
            "accuracy and missed detections."
        ),
    }

    qa_dir = run_dir / "qa"
    qa_dir.mkdir(
        parents=True,
        exist_ok=True,
    )
    (
        qa_dir / "validation.json"
    ).write_text(
        json.dumps(
            result,
            indent=2,
        ),
        encoding="utf-8",
    )

    print(
        json.dumps(
            result,
            indent=2,
        )
    )
    return not failures


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description=__doc__,
    )
    parser.add_argument(
        "--run",
        required=True,
        type=Path,
        help=(
            "Output folder produced by "
            "run_pipeline.py."
        ),
    )
    args = parser.parse_args()
    raise SystemExit(
        0
        if validate(args.run)
        else 1
    )
